# config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm

  mappings:
    tricks_image:
      uri_prefix: /images/tricks
      upload_destination: '%kernel.project_dir%/public/images/tricks'
    users_image:
      uri_prefix: /images/users
      upload_destination: '%kernel.project_dir%/public/images/users'
